// <auto-generated />
namespace BeerRecommender.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class region_abbreviations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(region_abbreviations));
        
        string IMigrationMetadata.Id
        {
            get { return "201711291928582_region_abbreviations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
