// <auto-generated />
namespace BeerRecommender.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class refactor_similarity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactor_similarity));
        
        string IMigrationMetadata.Id
        {
            get { return "201711152022226_refactor_similarity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
