// <auto-generated />
namespace BeerRecommender.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class inverse_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inverse_property));
        
        string IMigrationMetadata.Id
        {
            get { return "201712022124323_inverse_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
