// <auto-generated />
namespace BeerRecommender.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class parse_source_change_beers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(parse_source_change_beers));
        
        string IMigrationMetadata.Id
        {
            get { return "201711231750085_parse_source_change_beers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
