// <auto-generated />
namespace BeerRecommender.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserName_length_limit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserName_length_limit));
        
        string IMigrationMetadata.Id
        {
            get { return "201711072250234_UserName_length_limit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
